guru:
  jms:
    username: JMS Username
    password: somepass
    dbUrl: SomeUrl

---
spring:
  profiles: de
guru:
  jms:
    username: JMS Username--IN-GERMAN
    password: somepass
    dbUrl: SomeUrl
